pipeline {
    agent {
	docker {image 'node:16-alpine'}
    }

    stages {
        stage('Test') {
            steps {
                sh 'node --version'
                sh 'npm install -g npm'
                sh 'cd /var/lib/jenkins/workspace/'
                sh 'npm install'
                
            }
        }
    }
}

