pipeline {
    agent {
	docker {image 'node:16-alpine'}
    }

    stages {
        stage('Test') {
            steps {
                sh 'node --version'
                sh 'cat /etc/passwd'
                sh 'npm --version'
                sh 'cat /etc/passwd'
                git branch: 'jenkins-branch', url: 'https://github.com/jimihunter2002/i2Test'
                sh 'cd /var/lib/jenkins/workspace/jimi-first-pipeline'
                sh 'ls -a'
                sh  'sudo chown -R 117:126 "/.npm"'
                sh 'npm install'
            }
        }
    }
}

